# version: '3.3'
services:
  db:
    image: mysql:8.4.3
    environment:
      MYSQL_DATABASE: 'products-api-db'
      # So you don't have to use root, but you can if you like, por defecto crea un usuario root, por lo que sea crea nuevamente, solo hace falta establecer su contraseña
      # MYSQL_USER: ''
      # You can use whatever password you like
      # MYSQL_PASSWORD: ''
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    # No hace falta, porque en el Dockerfile ya genera la imagen de node (FROM node:23-alpine)
    # image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    # Para ejecutar el proyecto con nodemon
    command: npm run init
# Names our volume
volumes:
  db-data: